name: py310_hug
channels:
  - pytorch
  - sdvillal
  - huggingface
  - anaconda
  - nvidia/label/cuda-11.7.0
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ansicon=1.89.0=py310h5588dad_6
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - blessed=1.19.1=pyh95a074a_2
  - blosc=1.21.3=h6c2663c_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.5.7=h56e8100_0
  - cachecontrol=0.12.11=pyhd8ed1ab_1
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - cfitsio=3.470=h2bbff1b_7
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.0.4=py310haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.6=py310haa95532_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.3.15=pyhd8ed1ab_0
  - cryptography=39.0.1=py310h21b164f_0
  - cuda=11.7.0=0
  - cuda-cccl=11.7.58=0
  - cuda-command-line-tools=11.7.0=0
  - cuda-compiler=11.7.0=0
  - cuda-cudart=11.7.60=0
  - cuda-cudart-dev=11.7.60=0
  - cuda-cuobjdump=11.7.50=0
  - cuda-cupti=11.7.50=0
  - cuda-cuxxfilt=11.7.50=0
  - cuda-demo-suite=12.1.55=0
  - cuda-documentation=11.7.50=0
  - cuda-libraries=11.7.0=0
  - cuda-libraries-dev=11.7.0=0
  - cuda-memcheck=11.7.50=0
  - cuda-nsight-compute=11.7.0=0
  - cuda-nvcc=11.7.64=0
  - cuda-nvdisasm=11.7.50=0
  - cuda-nvml-dev=11.7.50=0
  - cuda-nvprof=11.7.50=0
  - cuda-nvprune=11.7.50=0
  - cuda-nvrtc=11.7.50=0
  - cuda-nvrtc-dev=11.7.50=0
  - cuda-nvtx=11.7.50=0
  - cuda-nvvp=11.7.50=0
  - cuda-runtime=11.7.0=0
  - cuda-sanitizer-api=11.7.50=0
  - cuda-toolkit=11.7.0=0
  - cuda-tools=11.7.0=0
  - cuda-visual-tools=11.7.0=0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cudnn=8.2.1=cuda11.3_0
  - cytoolz=0.12.0=py310h2bbff1b_0
  - dask-core=2022.7.0=py310haa95532_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dateutils=0.6.12=py_0
  - deepdiff=6.3.0=pyhd8ed1ab_0
  - distlib=0.3.6=pyhd8ed1ab_0
  - dulwich=0.21.3=py310h2bbff1b_0
  - eigen=3.3.7=h59b6b97_1
  - fastapi=0.88.0=pyhd8ed1ab_0
  - ffmpeg=4.2.2=he774522_0
  - filelock=3.9.0=py310haa95532_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - fsspec=2022.11.0=py310haa95532_0
  - geos=3.10.2=h39d44d4_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h5py=3.7.0=py310hfc34f40_0
  - hdf5=1.10.6=h1756f20_1
  - html5lib=1.1=pyh9f0ad1d_0
  - huggingface_hub=0.14.1=py_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - imagecodecs=2021.8.26=py310h4c966c4_2
  - imageio=2.26.0=py310haa95532_0
  - importlib-metadata=6.0.0=py310haa95532_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=haa95532_3556
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.2.3=pyhd8ed1ab_0
  - jarowinkler=1.2.0=py310h8a704f9_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinxed=1.2.0=pyh95a074a_0
  - joblib=1.1.1=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jxrlib=1.1=he774522_2
  - keyring=23.13.1=py310h5588dad_0
  - lazy-property=0.0.1=pyh9f0ad1d_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=12.0.0=default_h627e005_2
  - libcublas=11.10.1.25=0
  - libcublas-dev=11.10.1.25=0
  - libcufft=10.7.2.50=0
  - libcufft-dev=10.7.2.50=0
  - libcurand=10.2.10.50=0
  - libcurand-dev=10.2.10.50=0
  - libcusolver=11.3.5.50=0
  - libcusolver-dev=11.3.5.50=0
  - libcusparse=11.7.3.50=0
  - libcusparse-dev=11.7.3.50=0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libnpp=11.7.3.21=0
  - libnpp-dev=11.7.3.21=0
  - libnvjpeg=11.7.2.34=0
  - libnvjpeg-dev=11.7.2.34=0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - libzopfli=1.0.3=ha925a31_0
  - lightning=2.0.2=pyhd8ed1ab_0
  - lightning-cloud=0.5.36=pyhd8ed1ab_0
  - lightning-utilities=0.8.0=pyhd8ed1ab_0
  - locket=1.0.0=py310haa95532_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-binutils=2.25.1=5
  - m2w64-bzip2=1.0.6=6
  - m2w64-crt-git=5.0.0.4636.2595836=2
  - m2w64-gcc=5.3.0=6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-headers-git=5.0.0.4636.c0ad18a=2
  - m2w64-isl=0.16.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-mpc=1.0.3=3
  - m2w64-mpfr=3.1.4=4
  - m2w64-windows-default-manifest=6.4=3
  - m2w64-winpthreads-git=5.0.0.4634.697f757=2
  - m2w64-zlib=1.2.8=10
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310he2412df_1
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py310h476a331_0
  - msys2-conda-epoch=20160418=1
  - networkx=2.8.4=py310haa95532_0
  - nsight-compute=2022.2.0.13=0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy=1.23.5=py310h60c9a35_0
  - numpy-base=1.23.5=py310h04254f7_0
  - opencv=4.6.0=py310h4ed8f06_3
  - openjpeg=2.4.0=h4fc8c34_0
  - openslide=20171122=0
  - openssl=1.1.1u=h2bbff1b_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - orjson=3.8.14=py310h48ea969_0
  - packaging=22.0=py310haa95532_0
  - pandas=1.5.3=py310h4ed8f06_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=hd77b12b_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pillow=9.4.0=py310hd77b12b_0
  - pip=23.0.1=py310haa95532_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - poetry=1.4.2=win_pyhd8ed1ab_0
  - poetry-core=1.5.2=pyhd8ed1ab_0
  - poetry-plugin-export=1.3.1=pyhd8ed1ab_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - protobuf=3.20.3=py310hd77b12b_0
  - psutil=5.9.1=py310he2412df_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.9.2=py310he2412df_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py310he2412df_1
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.9=h966fe2a_2
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-editor=1.0.4=py_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h67b0de4_1
  - pytorch-lightning=2.0.2=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py310haa95532_0
  - pywavelets=1.4.1=py310h2bbff1b_0
  - pywin32-ctypes=0.2.0=py310h5588dad_1006
  - pyyaml=6.0=py310h2bbff1b_1
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h3ad3cdb_4
  - rapidfuzz=2.4.3=py310h8a704f9_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - regex=2022.7.9=py310h2bbff1b_0
  - requests=2.28.1=py310haa95532_0
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0
  - rich=13.3.5=pyhd8ed1ab_0
  - sacremoses=master=py_0
  - scikit-image=0.19.3=py310hd77b12b_1
  - scikit-learn=1.2.1=py310hd77b12b_0
  - scipy=1.10.0=py310hb9afe5d_1
  - setuptools=65.6.3=py310haa95532_0
  - shapely=1.8.1=py310h3578588_0
  - shellingham=1.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.1=h2bbff1b_0
  - starlette=0.22.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.12=h2bbff1b_0
  - tokenizers=0.11.4=py310he5181cf_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.8=pyha770c72_0
  - toolz=0.12.0=py310haa95532_0
  - torchmetrics=0.11.4=pyhd8ed1ab_0
  - tqdm=4.65.0=py310h9909e9c_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - transformers=4.28.1=py_0
  - trove-classifiers=2023.5.24=pyhd8ed1ab_0
  - typing-extensions=4.4.0=py310haa95532_0
  - typing_extensions=4.4.0=py310haa95532_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py310haa95532_0
  - uvicorn=0.22.0=py310h5588dad_0
  - vc=14.2=h21ff451_1
  - virtualenv=20.16.5=py310h5588dad_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.2=pyhd8ed1ab_0
  - websockets=10.3=py310he2412df_0
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zfp=0.5.5=hd77b12b_6
  - zipp=3.11.0=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - contourpy==1.0.7
      - cycler==0.11.0
      - fonttools==4.39.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - opencv-python==4.7.0.72
      - openslide-python==1.2.0
      - pyparsing==3.0.9
      - staintools==2.1.2
      - torchaudio==0.13.1
      - torchnet==0.0.4
      - torchvision==0.14.1
      - tornado==6.3.2
      - visdom==0.2.4
prefix: C:\Users\cielm\anaconda3\envs\py310_hug
